/* Bloxis – språk. Svenska är källspråket; engelskan översätter allt
   spelarvänt. Nycklar som saknas i en ordbok faller tillbaka till sv,
   och it_/ach_/world_-nycklar faller tillbaka till inline-namnen. */
(function (global) {
  'use strict';

  var sv = {
    tagline: 'Ett förtrollat blockäventyr',
    menuEndless: 'Oändligt läge',
    menuLevels: 'Banor',
    menuDaily: 'Dagens utmaning',
    menuQuests: 'Veckouppdrag',
    menuHelp: 'Så spelar du',
    record: 'Rekord:',

    chooserTitle: 'Oändligt läge',
    boardSize: 'Brädstorlek',
    difficulty: 'Svårighet',
    diffEasy: '🌱 Lätt',
    diffClassic: '🎯 Klassisk',
    diffHard: '🔥 Svår',
    chooserHint: 'Större bräde ger mer plats. Lätt och Klassisk börjar med enkla former och släpper in svårare efter hand – Svår kör alla former direkt.',
    start: 'Starta',

    close: 'Stäng',
    done: 'Klart',
    go: 'Kör!',
    goContinue: 'Fortsätt',
    letsGo: 'Nu kör vi!',
    playAgain: 'Spela igen',
    changeMode: 'Ändra läge',
    toMenu: 'Till menyn',
    toMap: 'Till kartan',
    tryAgain: 'Försök igen',
    back: 'Tillbaka',
    cancel: 'Avbryt',

    guide: 'Guide',
    playGuide: 'Spela guiden',
    levelN: 'Bana {n}',
    movesLeft: '{n} drag kvar',
    nLeft: '{n} kvar',
    hudGoal: '🎯 Mål: <b>{n}</b> p',

    objScore: '🎯 Nå <b>{target} poäng</b> på högst <b>{moves} drag</b>.',
    objScoreSub: 'Rensa flera linjer samtidigt och kedja rensningar för kombobonus.',
    objGems: '💎 Rensa alla <b>{n} ädelstenar</b> på högst <b>{moves} drag</b>.',
    objGemsSub: 'En ädelsten försvinner när dess rad eller kolumn blir full.',
    objIce: '🧊 Rensa all is (<b>{n} rutor</b>) på högst <b>{moves} drag</b>.',
    objIceSub: 'Is kräver <b>två</b> rensningar: den första spräcker isen, den andra tar bort den.',
    objCollect: 'Samla <b>{n} {color} block</b> på högst <b>{moves} drag</b>.',
    objCollectSub: 'Ett block räknas när det <b>rensas</b> i en full rad eller kolumn. Minst en pjäs i målfärgen finns alltid bland dina tre.',
    objSand: 'Rensa all <b>sand</b> ({n} rutor) på högst <b>{moves} drag</b>.',
    objSandSub: 'Sanden <b>sprider sig</b> till en tom granne var {every}:e drag – rensa den snabbare än den växer!',
    objMist: 'Lyft all <b>stjärndimma</b> ({n} rutor) på högst <b>{moves} drag</b>.',
    objMistSub: 'Det går inte att bygga i dimman – men en <b>rensning i rutan intill</b> blåser bort den.',
    objEggs: 'Rädda alla <b>{n} drakägg</b> innan de kläcks!',
    objEggsSub: 'Varje ägg har en <b>nedräkning</b> ({timer} drag). Rensa äggets rad eller kolumn i tid – kläcks ett ägg är banan förlorad.',
    objGhosts: 'Fånga alla <b>{n} andar</b> på högst <b>{moves} drag</b>.',
    objGhostsSub: 'Andarna <b>svävar</b> till en ny ruta var {every}:e drag – rensa raden eller kolumnen där en ande står innan den smiter!',
    objKeys: 'Samla alla <b>{n} nycklar</b> på högst <b>{moves} drag</b>.',
    objKeysSub: 'Låsen kan <b>inte rensas</b> och står i vägen tills alla nycklar är samlade – då krossas de på en gång.',

    colorName0: 'röda', colorName1: 'orange', colorName2: 'gula', colorName3: 'gröna',
    colorName4: 'ljusblå', colorName5: 'blå', colorName6: 'lila', colorName7: 'rosa',

    gameOverTitle: 'Spelet är slut!',
    newRecord: '🎉 Nytt rekord!',
    wellPlayed: 'Bra spelat!',
    loseTitle: 'Det gick inte den här gången',
    loseMoves: 'Dragen tog slut innan målet nåddes.',
    loseStuck: 'Ingen pjäs fick plats på brädet.',
    loseEgg: 'Ett drakägg kläcktes! Rensa äggens rader eller kolumner innan nedräkningen når noll.',
    loseMovesDaily: 'Dragen tog slut. Du kan försöka igen så många gånger du vill!',
    loseStuckDaily: 'Ingen pjäs fick plats på brädet. Försök igen!',
    levelCleared: 'Bana {n} klarad!',
    dailyCleared: 'Utmaning klarad!',
    dailyWonTitle: 'Dagens utmaning klarad!',
    dailySame: '<b>{date}</b> – samma bana för alla, ny varje dag!',
    streak: '🔥 Streak: <b>{n}</b> dagar',

    questWeek: 'Uppdragen byts varje måndag •',
    questWeekShort: 'vecka',
    questDone: 'Uppdrag klart',
    questClaimHint: 'hämta belöningen i menyn!',
    questClaim: 'Hämta',
    quest_lines: 'Rensa {n} linjer',
    quest_multi: 'Rensa 2+ linjer i ett drag {n} gånger',
    quest_combo3: 'Nå kombo ×3 {n} gånger',
    quest_wins: 'Klara {n} banor',
    quest_stars: 'Tjäna {n} stjärnor',
    quest_daily: 'Klara {n} dagliga utmaningar',
    quest_boosters: 'Använd {n} boosters',
    quest_endless: 'Nå {n} p i ett oändligt parti',

    settingsTitle: '⚙️ Inställningar',
    setSound: '🔊 Ljudeffekter',
    setMusic: '🎵 Musik',
    setVibration: '📳 Vibration',
    setColorblind: '👁️ Färgblindläge',
    setLanguage: '🌐 Språk',

    achTitle: '🏅 Utmärkelser',
    chestOpened: '🎉 Kistan öppnad: +{n} 💰',
    unlockReq: '🏅 Lås upp "{name}": {desc}',
    achievementBadge: '🏅 Utmärkelse',

    wardTitle: '🎩 Garderob',
    wardCoins: 'Dina mynt:',
    wardHats: 'Hattar', wardItems: 'Föremål', wardBack: 'Rygg',
    wardFace: 'Ansikte', wardColors: 'Färger', wardEyes: 'Ögonfärg',
    wardChosen: '✓ Vald', wardSwap: 'Byt', wardFree: 'Gratis',
    buyTitle: 'Köpa {name}?',
    buyPreview: 'Så här skulle det se ut!',
    buyPrice: 'Pris: <b>{price}</b> 💰 &ensp;•&ensp; Du har: <b>{coins}</b> 💰',
    buyMissing: 'Du behöver {n} 💰 till – spela banor och utmaningar!',
    buyBtn: 'Köp – {n} mynt',
    bought: '🎉 {name} köpt!',

    helpTitle: 'Så spelar du',
    help1: '<b>Dra</b> pjäserna från lådan och släpp dem på brädet.',
    help2: 'Fyll en hel <b>rad eller kolumn</b> så rensas den och ger poäng.',
    help3: 'Rensa flera linjer samtidigt och kedja ihop rensningar för <b>kombopoäng</b>.',
    help4: '<b>🧊 Is</b> kräver två rensningar. <b>💎 Ädelstenar</b> rensas med sin rad.',
    help5: '{sand} <b>Sand</b> sprider sig om den får stå. {mist} <b>Stjärndimma</b> lyfts av en rensning intill. {egg} <b>Drakägg</b> måste rensas innan nedräkningen når noll.',
    help6: '{ghost} <b>Andar</b> svävar till en ny ruta med jämna mellanrum. {key} <b>Nycklar</b> öppnar {lock} <b>låsen</b> – lås kan inte rensas förrän alla nycklar är samlade.',
    help7: '<b>Boosters</b> köps med mynt: 🔨 ta bort ett block, 💣 spräng 3&times;3, 🔄 byt pjäser, ↩️ ångra.',
    help8: 'Mynt tjänar du på banor, dagliga utmaningar, veckouppdrag och utmärkelser.',

    praise3: 'MÄSTERLIGT!',
    praise2: 'FANTASTISKT!',
    praiseCombo: 'Kombo x{n}!',

    needCoins: 'Du behöver {n} 💰 – spela banor och utmaningar!'
  };

  var en = {
    tagline: 'An enchanted block adventure',
    menuEndless: 'Endless mode',
    menuLevels: 'Levels',
    menuDaily: "Today's challenge",
    menuQuests: 'Weekly quests',
    menuHelp: 'How to play',
    record: 'Best:',

    chooserTitle: 'Endless mode',
    boardSize: 'Board size',
    difficulty: 'Difficulty',
    diffEasy: '🌱 Easy',
    diffClassic: '🎯 Classic',
    diffHard: '🔥 Hard',
    chooserHint: 'A bigger board gives more room. Easy and Classic start with simple shapes and phase in harder ones – Hard uses every shape from the start.',
    start: 'Start',

    close: 'Close',
    done: 'Done',
    go: "Go!",
    goContinue: 'Continue',
    letsGo: "Let's go!",
    playAgain: 'Play again',
    changeMode: 'Change mode',
    toMenu: 'To the menu',
    toMap: 'To the map',
    tryAgain: 'Try again',
    back: 'Back',
    cancel: 'Cancel',

    guide: 'Guide',
    playGuide: 'Play the guide',
    levelN: 'Level {n}',
    movesLeft: '{n} moves left',
    nLeft: '{n} left',
    hudGoal: '🎯 Goal: <b>{n}</b> pts',

    objScore: '🎯 Reach <b>{target} points</b> within <b>{moves} moves</b>.',
    objScoreSub: 'Clear several lines at once and chain clears for combo bonuses.',
    objGems: '💎 Clear all <b>{n} gems</b> within <b>{moves} moves</b>.',
    objGemsSub: 'A gem is collected when its row or column is completed.',
    objIce: '🧊 Clear all ice (<b>{n} tiles</b>) within <b>{moves} moves</b>.',
    objIceSub: 'Ice needs <b>two</b> clears: the first cracks it, the second removes it.',
    objCollect: 'Collect <b>{n} {color} blocks</b> within <b>{moves} moves</b>.',
    objCollectSub: 'A block counts when it is <b>cleared</b> in a full row or column. At least one piece in the target colour is always among your three.',
    objSand: 'Clear all the <b>sand</b> ({n} tiles) within <b>{moves} moves</b>.',
    objSandSub: 'The sand <b>spreads</b> to an empty neighbour every {every} moves – clear it faster than it grows!',
    objMist: 'Lift all the <b>star mist</b> ({n} tiles) within <b>{moves} moves</b>.',
    objMistSub: "You can't build in the mist – but a <b>clear right next to it</b> blows it away.",
    objEggs: 'Save all <b>{n} dragon eggs</b> before they hatch!',
    objEggsSub: 'Each egg has a <b>countdown</b> ({timer} moves). Clear its row or column in time – if an egg hatches, the level is lost.',
    objGhosts: 'Catch all <b>{n} spirits</b> within <b>{moves} moves</b>.',
    objGhostsSub: 'The spirits <b>drift</b> to a new tile every {every} moves – clear the row or column they stand in before they slip away!',
    objKeys: 'Collect all <b>{n} keys</b> within <b>{moves} moves</b>.',
    objKeysSub: "Locks <b>can't be cleared</b> and stay in the way until every key is collected – then they all shatter at once.",

    colorName0: 'red', colorName1: 'orange', colorName2: 'yellow', colorName3: 'green',
    colorName4: 'light blue', colorName5: 'blue', colorName6: 'purple', colorName7: 'pink',

    gameOverTitle: "Game over!",
    newRecord: '🎉 New record!',
    wellPlayed: 'Well played!',
    loseTitle: "Not this time",
    loseMoves: 'You ran out of moves before reaching the goal.',
    loseStuck: 'No piece could fit on the board.',
    loseEgg: 'A dragon egg hatched! Clear the egg rows or columns before the countdown hits zero.',
    loseMovesDaily: 'You ran out of moves. You can retry as many times as you like!',
    loseStuckDaily: 'No piece could fit on the board. Try again!',
    levelCleared: 'Level {n} cleared!',
    dailyCleared: 'Challenge cleared!',
    dailyWonTitle: "Today's challenge cleared!",
    dailySame: '<b>{date}</b> – the same level for everyone, new every day!',
    streak: '🔥 Streak: <b>{n}</b> days',

    questWeek: 'Quests change every Monday •',
    questWeekShort: 'week',
    questDone: 'Quest complete',
    questClaimHint: 'claim your reward in the menu!',
    questClaim: 'Claim',
    quest_lines: 'Clear {n} lines',
    quest_multi: 'Clear 2+ lines in one move {n} times',
    quest_combo3: 'Reach combo ×3 {n} times',
    quest_wins: 'Clear {n} levels',
    quest_stars: 'Earn {n} stars',
    quest_daily: 'Clear {n} daily challenges',
    quest_boosters: 'Use {n} boosters',
    quest_endless: 'Score {n} pts in one endless run',

    settingsTitle: '⚙️ Settings',
    setSound: '🔊 Sound effects',
    setMusic: '🎵 Music',
    setVibration: '📳 Vibration',
    setColorblind: '👁️ Colour-blind mode',
    setLanguage: '🌐 Language',

    achTitle: '🏅 Achievements',
    chestOpened: '🎉 Chest opened: +{n} 💰',
    unlockReq: '🏅 Unlock "{name}": {desc}',
    achievementBadge: '🏅 Achievement',

    wardTitle: '🎩 Wardrobe',
    wardCoins: 'Your coins:',
    wardHats: 'Hats', wardItems: 'Items', wardBack: 'Back',
    wardFace: 'Face', wardColors: 'Colours', wardEyes: 'Eye colour',
    wardChosen: '✓ Chosen', wardSwap: 'Wear', wardFree: 'Free',
    buyTitle: 'Buy {name}?',
    buyPreview: "Here's how it would look!",
    buyPrice: 'Price: <b>{price}</b> 💰 &ensp;•&ensp; You have: <b>{coins}</b> 💰',
    buyMissing: 'You need {n} more 💰 – play levels and challenges!',
    buyBtn: 'Buy – {n} coins',
    bought: '🎉 {name} purchased!',

    helpTitle: 'How to play',
    help1: '<b>Drag</b> the pieces from the tray and drop them on the board.',
    help2: 'Fill a whole <b>row or column</b> to clear it and score points.',
    help3: 'Clear several lines at once and chain clears for <b>combo points</b>.',
    help4: '<b>🧊 Ice</b> needs two clears. <b>💎 Gems</b> are collected with their line.',
    help5: '{sand} <b>Sand</b> spreads if left alone. {mist} <b>Star mist</b> lifts when you clear next to it. {egg} <b>Dragon eggs</b> must be cleared before the countdown hits zero.',
    help6: '{ghost} <b>Spirits</b> drift to a new tile now and then. {key} <b>Keys</b> open the {lock} <b>locks</b> – locks can\'t be cleared until every key is collected.',
    help7: '<b>Boosters</b> cost coins: 🔨 remove one block, 💣 blast 3&times;3, 🔄 swap pieces, ↩️ undo.',
    help8: 'Earn coins from levels, daily challenges, weekly quests and achievements.',

    praise3: 'MASTERFUL!',
    praise2: 'FANTASTIC!',
    praiseCombo: 'Combo x{n}!',

    needCoins: 'You need {n} 💰 – play levels and challenges!',

    /* Världar */
    world_0: 'Green Meadows', world_1: 'Frost Peaks', world_2: 'Sunset Desert',
    world_3: 'Starry Sky', world_4: 'Dragon Mountain', world_5: 'Whispering Woods',
    world_6: 'Crystal Cavern',

    /* Utmärkelser */
    ach_first_clear_n: 'First sweep', ach_first_clear_d: 'Clear your first line',
    ach_double_n: 'Double blast', ach_double_d: 'Clear 2 lines in one move',
    ach_triple_n: 'Triple boom', ach_triple_d: 'Clear 3+ lines in one move',
    ach_combo3_n: 'Combo king', ach_combo3_d: 'Reach combo x3',
    ach_combo5_n: 'Combo master', ach_combo5_d: 'Reach combo x5',
    ach_score1k_n: 'Thousand club', ach_score1k_d: '1000 pts in one endless run',
    ach_score5k_n: 'High roller', ach_score5k_d: '5000 pts in one endless run',
    ach_levels10_n: 'Wanderer', ach_levels10_d: 'Clear 10 levels',
    ach_world1_n: 'Meadow master', ach_world1_d: 'Three stars on every level in world 1',
    ach_boosters_n: 'Toolbox', ach_boosters_d: 'Use all four boosters',
    ach_daily1_n: 'Hero of the day', ach_daily1_d: 'Clear a daily challenge',
    ach_streak3_n: 'On a roll', ach_streak3_d: '3-day streak in the daily challenge',

    /* Garderob – hattar */
    it_ingen: 'None', it_wizard: 'Wizard hat', it_blomster: 'Flower crown',
    it_svamp: 'Mushroom cap', it_tomte: 'Santa hat', it_pirat: 'Pirate bandana',
    it_viking: 'Viking helmet', it_haxa: 'Witch hat', it_riddare: 'Knight helmet',
    it_gloria: 'Halo', it_krona: 'Gold crown', it_lagerkrans: 'Laurel wreath',
    it_mankrona: 'Moon crown',
    /* föremål */
    it_fana: 'Adventure pennant', it_stav: 'Magic wand', it_skold: 'Shield',
    it_lykta: 'Lantern', it_yxa: 'Axe', it_kristall: 'Crystal ball',
    it_svard: 'Sword', it_bok: 'Spellbook', it_manstav: 'Moon staff',
    it_spira: 'Star sceptre',
    /* rygg */
    it_cape: 'Red cape', it_alvvingar: 'Fairy wings', it_fjaril: 'Butterfly wings',
    it_stjarnmantel: 'Star cloak', it_drakvingar: 'Dragon wings',
    /* ansikte */
    it_kinder: 'Rosy cheeks', it_fraknar: 'Freckles', it_glasogon: 'Glasses',
    it_ogonlapp: 'Eye patch', it_monokel: 'Monocle', it_stjarnkind: 'Star cheek',
    /* färger */
    it_rosa: 'Pink', it_gron: 'Fairy green', it_bla: 'Sky blue', it_gul: 'Sun yellow',
    it_lila: 'Twilight purple', it_eld: 'Fire red', it_hav: 'Ocean blue',
    it_smaragd: 'Emerald', it_korall: 'Coral', it_korsbar: 'Cherry',
    it_frost: 'Frost white', it_natt: 'Night black', it_guld: 'Golden',
    it_drake: 'Dragonscale',
    /* ögon */
    it_brun: 'Brown', it_blaogon: 'Blue', it_gronogon: 'Green', it_gra: 'Grey',
    it_barnsten: 'Amber', it_violett: 'Violet', it_turkos: 'Turquoise',
    it_rubin: 'Ruby', it_is: 'Ice blue', it_guldogon: 'Golden eyes',
    it_stjarnogon: 'Star eyes'
  };

  global.BloxisLang = { sv: sv, en: en };
})(this);
